sudo: false
language: rust
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

# run builds for all the trains (and more)
rust:
  - beta
  - stable

# load cargo-travis
before_script:
  - |
      cargo install cargo-travis &&
      export PATH=$HOME/.cargo/bin:$PATH

# the main build
script:
  - |
      cargo build &&
      cargo test &&
      cargo bench     

after_success: 
  - cargo coveralls

env:
  global:
    - RUST_TEST_THREADS=1
