[package]
name = "bugsnag-api"
version = "0.1.0"
authors = ["Bastian Köcher <git@kchr.de>"]

[dependencies]
hyper = "0.5"
backtrace = "0.3"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
serde_test = "0.9"
sys-info = "0.4.1"